// lib/core/services/ask_iman_ai_service.dart
//
// Client-side ASK Iman AI.
// Calls the Gemini API directly over HTTPS (no Cloud Functions / no Blaze)
// and grounds Quran + Hadith authenticity checks against live public corpora.
//
// SAFETY: citations are only ever emitted from corpus retrieval results,
// never generated by the model. Unmatched text always gets the honest
// "I cannot verify" answer instead of an invention.

import 'dart:async';
import 'dart:convert';
import 'dart:collection';
import 'dart:io';

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';
import 'package:google_mlkit_text_recognition/google_mlkit_text_recognition.dart';
import 'package:http/http.dart' as http;
import 'package:image_picker/image_picker.dart';
import 'package:path_provider/path_provider.dart';
import 'package:permission_handler/permission_handler.dart';
import 'package:shared_preferences/shared_preferences.dart';
import 'package:speech_to_text/speech_to_text.dart';

// ── Configuration ────────────────────────────────────────────────────────────
// The API key is injected at build time via --dart-define=GEMINI_API_KEY=...
// When the app is launched without that flag (e.g. Android Studio's Run ▶
// button), it falls back to the git-ignored asset assets/secrets/gemini.key,
// loaded once at startup by bootstrap().
const String _apiKey = String.fromEnvironment('GEMINI_API_KEY');

const String _model = String.fromEnvironment(
  'ASKIMAN_MODEL',
  defaultValue: 'gemini-3.6-flash',
);

const String _genBase =
    'https://generativelanguage.googleapis.com/v1beta/models';

const int kDayLimit = 30; // soft per-device quota
const int kMinuteLimit = 5;

const double _arMinScore = 0.58; // broad recall sweep
const double _latinMinScore = 0.62;

// Strict acceptance: a verified verdict is ONLY emitted when the top corpus
// hit clears these bars AND clearly dominates the runner-up (no ties → no
// "first match wins" guesses for common fragments).
const double _arStrictScore = 0.92;
const double _arStrictContainment = 0.85;
const double _arStrictGap = 0.08;
const double _latinStrictScore = 0.75;
const double _latinStrictContainment = 0.70;
const double _latinStrictGap = 0.10;

// Medium band: below strict but with a plausible shortlist → grounded
// adjudicator call may confirm a paraphrase/translation.
const double _arAdjudicateMin = 0.60;
const double _latinAdjudicateMin = 0.50;

const Map<String, String> _quranEditions = {
  'ara': 'quran-uthmani-hafs',
  'eng': 'en.sahih',
  'urd': 'ur.ahmedali',
};

const List<Map<String, String>> hadithBooks = [
  {'slug': 'bukhari', 'name': 'Sahih al-Bukhari'},
  {'slug': 'muslim', 'name': 'Sahih Muslim'},
  {'slug': 'abudawud', 'name': 'Sunan Abi Dawud'},
  {'slug': 'tirmidhi', 'name': "Jami' at-Tirmidhi"},
  {'slug': 'nasai', 'name': "Sunan an-Nasa'i"},
  {'slug': 'ibnmajah', 'name': 'Sunan Ibn Majah'},
];

// ── Model classes ────────────────────────────────────────────────────────────
class AskAICitation {
  final String kind; // 'ayah' | 'hadith'
  final String book;
  final int? surahNumber;
  final String? surahName;
  final String? surahArabic;
  final int? ayahNumber;
  final int? hadithNumber;
  final String arabic;
  final String text; // ayah translation / hadith english text
  final String? grade;

  const AskAICitation({
    required this.kind,
    required this.book,
    this.surahNumber,
    this.surahName,
    this.surahArabic,
    this.ayahNumber,
    this.hadithNumber,
    this.arabic = '',
    this.text = '',
    this.grade,
  });

  factory AskAICitation.fromJson(Map<String, dynamic> j) {
    return AskAICitation(
      kind: j['kind'] as String? ?? 'hadith',
      book: j['book'] as String? ?? '',
      surahNumber: j['surahNumber'] as int?,
      surahName: j['surahName'] as String?,
      surahArabic: j['surahArabic'] as String?,
      ayahNumber: j['ayahNumber'] as int?,
      hadithNumber: j['hadithNumber'] as int?,
      arabic: j['arabic'] as String? ?? '',
      text: j['text'] as String? ?? '',
      grade: j['grade'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'kind': kind,
        'book': book,
        'surahNumber': surahNumber,
        'surahName': surahName,
        'surahArabic': surahArabic,
        'ayahNumber': ayahNumber,
        'hadithNumber': hadithNumber,
        'arabic': arabic,
        'text': text,
        'grade': grade,
      };

  String get shortLabel {
    if (kind == 'ayah') {
      return '$surahName ($surahArabic) $surahNumber:$ayahNumber';
    }
    return hadithNumber != null ? '$book — #$hadithNumber' : book;
  }
}

class AskAIResponse {
  final String verdict; // verified | unverified | refused | answer
  final String type; // quran | hadith | general_qna | out_of_scope
  final String answer;
  final List<AskAICitation> citations;
  final String lang;
  final String? errorCode; // set when the call was blocked before answering

  const AskAIResponse({
    required this.verdict,
    required this.type,
    required this.answer,
    this.citations = const [],
    this.lang = 'en',
    this.errorCode,
  });

  bool get isVerified => verdict == 'verified';
  bool get isBlocked => errorCode != null;

  factory AskAIResponse.fromJson(Map<String, dynamic> j) {
    return AskAIResponse(
      verdict: j['verdict'] as String? ?? 'unverified',
      type: j['type'] as String? ?? 'general_qna',
      answer: j['answer'] as String? ?? '',
      citations: ((j['citations'] as List?) ?? [])
          .whereType<Map>()
          .map((e) => AskAICitation.fromJson(Map<String, dynamic>.from(e)))
          .toList(),
      lang: j['lang'] as String? ?? 'en',
      errorCode: j['errorCode'] as String?,
    );
  }

  Map<String, dynamic> toJson() => {
        'verdict': verdict,
        'type': type,
        'answer': answer,
        'citations': citations.map((c) => c.toJson()).toList(),
        'lang': lang,
        'errorCode': errorCode,
      };
}

// ── Pure matching helpers (ported from functions/ai_tools.js) ───────────────
// Kept dependency-free so they can be unit tested.

final RegExp _diacritics =
    RegExp(r'[\u064B-\u065F\u0610-\u061A\u06D6-\u06DC\u06DF-\u06E8\u06EA-\u06ED\u0640\u0670\u0653-\u0655\u06E0\u06E1\u06E2\u06E3\u06E4\u06E5\u06E6\u06E7\u06E8\u06EC\u06ED]');
final RegExp _alefVariants = RegExp(r'[\u0622\u0623\u0625\u0671]');
final RegExp _nonLetterOrNumber = RegExp(r'[^\p{L}\p{N}\s]', unicode: true);

String _alefFix(String ch) {
  switch (ch) {
    case '\u0622':
    case '\u0623':
    case '\u0625':
    case '\u0671':
      return '\u0627';
    default:
      return ch;
  }
}

String normalizeForMatch(String text) {
  return text
      .replaceAll(_diacritics, '')
      .replaceAllMapped(_alefVariants, (m) => _alefFix(m[0]!))
      .replaceAll('\u0649', '\u064A') // alef maqsura -> ya
      .replaceAll('\u0629', '\u0647') // taa marbuta -> ha
      .replaceAll(_nonLetterOrNumber, ' ')
      .replaceAll(RegExp(r'\s+'), ' ')
      .trim()
      .toLowerCase();
}

List<String> _tokens(String text) =>
    normalizeForMatch(text).split(' ').where((t) => t.isNotEmpty).toList();

double containmentScore(String hayText, String needleText) {
  final th = _tokens(hayText);
  final tn = _tokens(needleText);
  if (th.isEmpty || tn.isEmpty) return 0;
  final sh = th.toSet();
  var hit = 0;
  for (final t in tn) {
    if (sh.contains(t)) hit++;
  }
  return hit / tn.length;
}

double overlapScore(String aText, String bText) {
  final ta = _tokens(aText);
  final tb = _tokens(bText);
  if (ta.isEmpty || tb.isEmpty) return 0;
  final sa = ta.toSet();
  final sb = tb.toSet();
  final inter = sa.where(sb.contains).length;
  return inter / (sa.length < sb.length ? sa.length : sb.length);
}

({double score, double containment, double overlap, double lenFactor})
    rankMatch({required String hayText, required String needleText}) {
  final c = containmentScore(hayText, needleText);
  final o = overlapScore(hayText, needleText);
  final n = normalizeForMatch(needleText);
  final h = normalizeForMatch(hayText);
  final lenFactor = n.length <= h.length
      ? 1.0
      : (n.isEmpty ? 0.0 : (1 - (n.length - h.length) / n.length).clamp(0.0, 1.0));
  final score = (c > o ? c : o) * lenFactor;
  return (score: score, containment: c, overlap: o, lenFactor: lenFactor);
}

bool isArabicScript(String text) => RegExp(r'[\u0600-\u06FF]').hasMatch(text);

class CorpusMatch {
  final dynamic item;
  final double score;
  final double containment;
  final double overlap;
  final double lenFactor;
  CorpusMatch(this.item, this.score, this.containment, this.overlap, this.lenFactor);
}

List<CorpusMatch> findMatches(
  List<dynamic> corpusItems, {
  required String Function(dynamic) textOf,
  required String needleText,
  required double minScore,
  int limit = 5,
}) {
  final out = <CorpusMatch>[];
  for (final item in corpusItems) {
    final r = rankMatch(hayText: textOf(item), needleText: needleText);
    if (r.score >= minScore) {
      out.add(CorpusMatch(item, r.score, r.containment, r.overlap, r.lenFactor));
    }
  }
  out.sort((a, b) => b.score.compareTo(a.score));
  return out.take(limit).toList();
}

/// A citation-worthy verdict requires the top hit to clear the strict score
/// AND containment bars AND dominate the runner-up by `gap`. Ties (e.g. a
/// common fragment appearing in many ayahs/hadiths) are deliberately refused
/// instead of guessing — guaranteeing the cited source is not out of context.
({bool ok, CorpusMatch? best}) strictAccept(
  List<CorpusMatch> hits, {
  required double strictScore,
  required double strictContainment,
  required double gap,
}) {
  if (hits.isEmpty) return (ok: false, best: null);
  final top = hits.first;
  final second = hits.length > 1 ? hits[1] : null;
  final ok = top.score >= strictScore &&
      top.containment >= strictContainment &&
      (second == null || (top.score - second.score) >= gap);
  return (ok: ok, best: ok ? top : null);
}

// ── Source-claim parsing ────────────────────────────────────────────────────
// When the user pins a location ("2:255", "surah al-baqarah verse 255",
// "sahih muslim hadith 345", "bukhari 1234") the quote is verified ONLY
// against that exact spot. A mismatch means "this is not in my knowledge" —
// we never cross-reference a different location than the one the user named.

/// Arabic-Indic digits (٠-٩) → ASCII for claim numbers.
String _arabicDigit(int cp) => '${cp - 0x0660}';

Map<String, int> surahNameIndex(Iterable items) {
  final idx = <String, int>{};
  for (final i in items) {
    final s = (i as Map)['surah'] as Map?;
    if (s == null) continue;
    final n = s['number'] as int?;
    if (n == null) continue;
    for (final name in [s['englishName'], s['meaning'], s['name']]) {
      if (name is String && name.isNotEmpty) {
        idx[normalizeForMatch(name).trim()] = n;
      }
    }
  }
  return idx;
}

int? _nameMatch(String raw, bool fromStart, Map<String, int> idx) {
  final p = normalizeForMatch(raw).trim();
  var bestLen = 0;
  int? bestNum;
  idx.forEach((k, n) {
    if (k.isEmpty || k.length <= bestLen) return;
    final ok = fromStart ? p.startsWith(k) : p.endsWith(k);
    if (ok) {
      bestLen = k.length;
      bestNum = n;
    }
  });
  return bestNum;
}

/// Extracts a pinned Quran location (surah, verse) from the message, or null.
(int, int)? parseQuranClaim(String input, Map<String, int> surahIndex) {
  final t =
      input.replaceAllMapped(RegExp(r'[٠-٩]'), (m) => _arabicDigit(m[0]!.codeUnitAt(0)));
  final lower = t.toLowerCase();

  // "2:255", "2/255", "2-255"
  final col = RegExp(r'(\d{1,2})\s*[:/-]\s*(\d{1,3})').firstMatch(lower);
  if (col != null) {
    final s = int.tryParse(col.group(1)!);
    final v = int.tryParse(col.group(2)!);
    if (s != null && v != null && s >= 1 && s <= 114 && v >= 1) return (s, v);
  }

  // "surah 2", "surah 18 ayah 10" …
  final sx = RegExp(r'(?:surah|sura|surat|chapter|سوره)\s+(\d{1,2})(?!\d)')
      .firstMatch(lower);
  if (sx != null) {
    final s = int.tryParse(sx.group(1)!);
    if (s == null || s < 1 || s > 114) return null;
    final rest = lower.substring(sx.end);
    final vx = RegExp(r'\d{1,4}').firstMatch(rest);
    final v = vx != null ? int.tryParse(vx.group(0)!) : null;
    if (v != null && v >= 1) return (s, v);
    return null;
  }

  // name forms: "al-baqarah 255", "ayah 255 of surah al baqarah"
  for (final m in RegExp(r'(\d{1,3})').allMatches(lower)) {
    final v = int.tryParse(m.group(1)!);
    if (v == null || v < 1) continue;
    final before = lower.substring(0, m.start);
    final end = m.end + 60 < lower.length ? m.end + 60 : lower.length;
    final after = lower
        .substring(m.end, end)
        .replaceFirst(
            RegExp(r'^(?:\s*(?:of|from|in|is|being)\s+)?(?:surah|sura|surat|سورة)\s*'),
            '');
    final sNo = _nameMatch(before, false, surahIndex) ??
        _nameMatch(after, true, surahIndex);
    if (sNo != null) return (sNo, v);
  }
  return null;
}

/// Extracts a pinned hadith reference (book slug, hadith number?) or null.
(String, int?)? parseHadithClaim(String input) {
  final lower = input.toLowerCase().replaceAll('-', ' ');
  for (final bk in hadithBooks) {
    final slug = bk['slug']!;
    final m = RegExp('${RegExp.escape(slug)}[^\\d]{0,30}?(\\d{1,5})')
        .firstMatch(lower);
    if (m != null) {
      return (slug, int.tryParse(m.group(1)!));
    }
  }
  return null;
}

// ── Topic-based source retrieval (for general Q&A enrichment) ───────────────
// When the user asks an Islamic-topic question ("is namaz necessary in Islam?"),
// we ground the answer by retrieving REAL Quran ayahs + hadith from the verified
// corpus (never invented), attach them as citations, and hand them to the model
// as VERIFIED REFERENCES it is allowed to quote. Gate + ranking are pure and so
// unit-testable without any network access.

/// Strong topic anchors: worship/fiqh words (as normalized by normalizeForMatch).
const List<String> _topicAnchors = [
  // prayer
  'salah', 'salat', 'salaah', 'namaz', 'namaz ka', 'prayer', 'prayers',
  'prayed', 'praying', 'pray', 'recite', 'recitation', 'tilawah', 'qirat',
  'نماز', 'صلى', 'صلاة', 'صلوة', 'تلاوت',
  // fasting
  'fasting', 'fast', 'roza', 'sawm', 'صيام', 'صوم', 'روزہ', 'روزه',
  // charity
  'zakat', 'zakah', 'zakaat', 'sadqah', 'sadaqah', 'sadaqa', 'charity',
  'give in charity', 'زکاۃ', 'زکاة', 'صدقہ', 'صدقة', 'خیرات',
  // hajj
  'hajj', 'haj', 'umrah', 'umra', 'حج', 'عمرہ',
  // purification
  'wudu', 'wudhu', 'ablution', 'ghusl', 'tayammum', 'وضو', 'غسل',
  // modesty
  'hijab', 'niqab', 'jilbab', 'khimar', 'modesty', 'حجاب', 'نقاب',
  // remembrance / supplication
  'dhikr', 'zikr', 'dua', 'duas', 'duaa', 'supplication', 'istighfar',
  'اذکار', 'دعا', 'ذکر',
  // creed
  'tawheed', 'tauheed', 'shirk', 'iman', 'tawbah', 'taubah', 'repentance',
  'توحید', 'شرک', 'ایمان', 'توبہ',
  // law / halal
  'halal', 'haram', 'riba', 'usury', 'nikah', 'talaq', 'mahr', 'fiqh',
  'حلال', 'حرام', 'ربا', 'نکاح', 'طلاق',
  // afterlife
  'jannah', 'jahannam', 'qiyamah', 'paradise', 'hellfire', 'جنت', 'جہنم',
  // worship practices
  'eid', 'adhan', 'azan', 'takbir', 'taraweeh', 'quran', 'sunnah',
  'sunna', 'deen', 'qiblah', 'sajdah', 'ruku', 'rakat', 'janazah',
  'قرآن', 'سنت', 'دین', 'عید', 'اذان',
  // cultural-religious nouns (roman urdu)
  'jenazah', 'laylat', 'kadr', 'qadar', 'asr', 'fajr', 'zuhr',
  'maghrib', 'isha', 'سورہ', 'آیت',
  // family & virtue topics
  'parents', 'mother', 'father', 'children', 'family', 'neighbor',
  'neighbours', 'orphan', 'widow', 'patience', 'sabr', 'kindness',
  'gratitude', 'thanksgiving', 'shukr', 'honesty', 'truthfulness',
  'trust', 'amanah', 'knowledge', 'ilm', 'learning', 'mercy', 'justice',
  'fairness', 'adl', 'forgiveness', 'purity', 'cleanliness', 'taqwa',
  'غفران', 'رحمت', 'صبر', 'والدین', 'والد', 'والدہ', 'شفقت', 'سچ',
  'علم', 'رحم', 'انصاف', 'maghfirah', 'muharram', 'rahim',
  'ماں', 'باپ', 'والدین', 'مہربانی', 'بدگمانی',
  // fiqh / rulings / halal-haram
  'ruling', 'rulings', 'rule', 'rules', 'ruled', 'law', 'laws', 'sharia',
  'shariah', 'fatwa', 'verdict', 'allowed', 'allow', 'allows', 'permissible',
  'forbidden', 'prohibited', 'prohibit', 'prohibits', 'banned', 'makruh',
  'wajib', 'fard', 'fardh', 'mustahab', 'mubah', 'bidah', 'bidat', 'innovation',
  'innovations', 'sin', 'sins', 'sinful', 'reward', 'rewards', 'punishment',
  'punish', 'punishes', 'punished', 'تاکید', 'حکم', 'عقوبت', 'ثواب', 'گناہ',
  // daily life / cultural questions
  'music', 'singing', 'song', 'songs', 'beard', 'shaving', 'trimming', 'gold',
  'silk', 'perfume', 'tattoo', 'tattoos', 'pork', 'alcohol', 'wine', 'gambling',
  'interest', 'dream', 'dreams', 'interpretation', 'jinn', 'magic', 'sihr',
  'evil eye', 'ruqya', 'amulets', 'fortune', 'astrology', 'چڑیل', 'سحر',
  'جھوٹ', 'غیبت', 'جھوٹی',
  // creed / afterlife / community
  'akhirah', 'aqeedah', 'aqida', 'kufr', 'kafir', 'taghut', 'polytheism',
  'umarah', 'ummah', 'brotherhood', 'guidance', 'misguidance', 'tawakkul',
  'reliance', 'خوف', 'امید', 'قیامت',
  'death', 'dying', 'burial', 'funeral', 'grave', 'grave punishment',
  'قبر', 'موت', 'نیند',
];

/// Weak domain words: mixed with >=2 other tokens they turn a question into an
/// Islamic-topic one even when no strong anchor matches.
const List<String> _weakDomainWords = [
  'islam', 'muslim', 'muslims', 'islamic', 'الله', 'اللہ', 'رسول', 'نبی',
  'islam ke', 'muslim ke',
];

const List<String> _topicStopWords = [
  'is', 'of', 'in', 'to', 'a', 'an', 'the', 'and', 'or', 'for', 'about',
  'with', 'from', 'me', 'my', 'i', 'you', 'your', 'we', 'they', 'do',
  'does', 'did', 'can', 'could', 'will', 'would', 'should', 'what', 'which',
  'how', 'why', 'who', 'when', 'where', 'please', 'tell', 'show', 'explain',
  'meaning', 'some', 'any', 'whats', 'are', 'am', 'be', 'been', 'isn',
  'was', 'were', 'at', 'on', 'as', 'it', 'its', 'so', 'if', 'than', 'then',
  'them', 'those', 'this', 'that', 'these', 'there', 'here', 'not', 'no',
  'hai', 'kya', 'ka', 'ki', 'ke', 'ko', 'aur', 'me', 'mein', 'ہے', 'کیا',
  'اور', 'کا', 'کی', 'کے', 'کو', 'میں', 'بھی', 'پر', 'سے',
];

bool _isArabicishToken(String t) => RegExp(r'[\u0600-\u06FF]').hasMatch(t);

/// True when the question is clearly an Islamic-topic request that deserves
/// grounded Quran/hadith sources (instead of a plain chat answer).
bool looksLikeIslamicTopic(String input) {
  final toks = _tokens(input).toSet();
  if (toks.isEmpty) return false;
  if (toks.any(_topicAnchors.contains)) return true;
  final weak = toks.where(_weakDomainWords.contains).toList();
  if (weak.isNotEmpty && toks.length >= 3) return true;
  // Explicit reference requests: "quran/hadith/ayat/surah/verse ... about X",
  // "what does the quran say about X" — always worth grounding with sources.
  final low = input.toLowerCase();
  if (RegExp(r'\b(quran|quranic|hadith|ayat|ayah|surah|verse)\b').hasMatch(low) &&
      RegExp(r'\b(about|regarding|on|concerning)\b').hasMatch(low)) {
    return true;
  }
  return false;
}

/// Query terms for corpus retrieval: topic anchors first, then non-stopword
/// content words (latin >=3 chars, arabic-script >=2 chars), deduplicated.
List<String> topicQueryTerms(String input) {
  final toks = _tokens(input);
  final anchors = <String>{};
  final content = <String>{};
  for (final t in toks) {
    if (_topicAnchors.contains(t)) {
      anchors.add(t);
    } else if (!_topicStopWords.contains(t) &&
        !RegExp(r'^\d+$').hasMatch(t) &&
        ((_isArabicishToken(t) && t.length >= 2) || t.length >= 3)) {
      content.add(t);
    }
  }
  return [...anchors, ...content];
}

/// Simple inverted index: normalized term -> item indices containing it.
Map<String, List<int>> buildTermIndex(List<String> texts) {
  final idx = <String, List<int>>{};
  for (var i = 0; i < texts.length; i++) {
    for (final t in _tokens(texts[i]).toSet()) {
      (idx[t] ??= []).add(i);
    }
  }
  return idx;
}

class TopicHit {
  final int index;
  final double score;
  final int matchedTerms;
  const TopicHit(this.index, this.score, this.matchedTerms);
}

/// idf-weighted ranking of corpus docs against the query terms. Terms already in
/// the topic-anchor list are double-weighted (they are the strongest signal).
List<TopicHit> topicRank(
    Map<String, List<int>> index, int docCount, List<String> terms) {
  final scored = <int, double>{};
  final cnt = <int, int>{};
  for (final raw in terms.toSet()) {
    final post = index[raw];
    if (post == null) continue;
    final w = _topicAnchors.contains(raw) ? 2.0 : 1.0;
    final idf = docCount / (post.length + 1.0);
    for (final d in post) {
      scored[d] = (scored[d] ?? 0) + idf * w;
      cnt[d] = (cnt[d] ?? 0) + 1;
    }
  }
  final docs = scored.keys.toList()
    ..sort((a, b) => (scored[b] ?? 0).compareTo(scored[a] ?? 0));
  return [
    for (final d in docs) TopicHit(d, scored[d] ?? 0, cnt[d] ?? 0),
  ];
}

/// Decides whether retrieved evidence is strong enough to attach sources.
/// The topic gate (`looksLikeIslamicTopic`) is the primary filter; here we only
/// require that ANY query term actually matched a corpus passage. If literally
/// nothing matched there is nothing to attach — otherwise we always enrich,
/// because the retrieved passage is real corpus text (never invented).
bool topicEvidenceConfident(List<String> terms, Iterable<int> matchedCounts) {
  var best = 0;
  for (final m in matchedCounts) {
    if (m > best) best = m;
  }
  return best >= 1;
}

/// Deterministic, verdict-first answer built ONLY from the model's short
/// verdict/explanation — the exact ayah/hadith text, Arabic, translation and
/// grade are rendered separately by the _CitationTile UI cards, so they must
/// NOT be duplicated here.  This keeps the answer text clean and repetition-free.
String buildSourcedAnswer({
  required String verdict,
  required List<AskAICitation> refs,
  String explanation = '',
}) {
  final sb = StringBuffer();
  void p(String s) {
    final t = s.trim();
    if (t.isEmpty) return;
    if (sb.isNotEmpty) {
      sb.writeln();
      sb.writeln();
    }
    sb.write(t);
  }

  p(verdict);
  if (refs.isNotEmpty) {
    final refLabels = refs.map((c) {
      if (c.kind == 'ayah') {
        return 'Surah ${c.surahName} ${c.surahNumber}:${c.ayahNumber}';
      }
      return c.hadithNumber != null
          ? '${c.book} #${c.hadithNumber}'
          : c.book;
    }).join(', ');
    p('\u2014 supported by $refLabels');
  }
  p(explanation);
  return sb.toString().trim();
}

// ── Service ─────────────────────────────────────────────────────────────────
class AskImanAiService {
  AskImanAiService._();

  static String? _deviceId;

  static String? _runtimeKey;

  /// Loads the API key from the git-ignored asset assets/secrets/gemini.key
  /// when no --dart-define key was baked in at build time.
  static Future<void> bootstrap() async {
    debugPrint('AI: bootstrap() called. _apiKey.isEmpty=${_apiKey.isEmpty}, _runtimeKey=null -> ${_runtimeKey == null}');
    if (_apiKey.isNotEmpty) {
      debugPrint('AI: using --dart-define key (length=${_apiKey.length}).');
      return;
    }
    if (_runtimeKey != null) {
      debugPrint('AI: _runtimeKey already set (length=${_runtimeKey!.length}).');
      return;
    }
    try {
      debugPrint('AI: loading asset assets/secrets/gemini.key …');
      final data = await rootBundle.loadString('assets/secrets/gemini.key');
      debugPrint('AI: asset raw length=${data.length}');
      final key = data.trim();
      debugPrint('AI: asset trimmed length=${key.length}, startsWith="AQ..."=${key.startsWith('AQ')}');
      if (key.isNotEmpty) {
        _runtimeKey = key;
        debugPrint('AI: _runtimeKey SET successfully (length=${_runtimeKey!.length}).');
      } else {
        debugPrint('AI: WARNING — asset content after trim() is EMPTY.');
        _runtimeKey = null;
      }
    } catch (e, st) {
      debugPrint('AI: EXCEPTION loading gemini.key asset: $e');
      debugPrint('AI: STACK: $st');
      _runtimeKey = null;
    }
  }

  static String get _effectiveApiKey =>
      _apiKey.isNotEmpty ? _apiKey : (_runtimeKey ?? '');

  static bool get isConfigured => _effectiveApiKey.isNotEmpty;
  static String get configModel => _model;

  // ── Cheap gate before any Gemini call ────────────────────────────────────
  // If the input clearly quotes a verse/hadith, verify it against the corpus
  // directly and skip the classifier (0 Gemini calls for real verifications).
  static bool _possibleQuote(String raw) {
    final t = raw.trim();
    if (t.length < 30) return false;
    final lower = t.toLowerCase();
    const lowKws = [
      'quran', 'surah', 'ayah', 'ayat', 'verse',
      'hadith', 'narrat', 'said the prophet',
      'قال الله', 'قال رسول',
    ];
    final hasKws = lowKws.any(lower.contains);
    if (hasKws) {
      // Question forms asking for an explanation/search (not a verification):
      // "can you tell me a quran ayat about x", "what does the quran say..."
      // Also verb-initial interrogatives ("is x obligatory in quran?") are
      // questions, NOT quotes — they must route to the sourced Q&A path.
      const questionPrefix =
          r'^(can you\b|what\b|which\b|tell me\b|explain\b|meaning of\b|how\b|why\b|is there\b|find me\b|give me\b|show me\b|quote me\b|a verse about\b|an ayah about\b|an ayat about\b|verse about\b|is\b|are\b|does\b|do\b|did\b|can\b|could\b|will\b|would\b|should\b|has\b|have\b|when\b|where\b|who\b)';
      if (RegExp(questionPrefix).hasMatch(lower)) {
        return false;
      }
      return true;
    }
    return isArabicScript(t);
  }

  static bool _looksLikeHadith(String raw) {
    final lower = raw.toLowerCase();
    const hadithWords = [
      'hadith', 'narrat', 'said the prophet',
      'قال رسول', 'روى', 'حديث', 'الرسول', 'بخاري',
    ];
    return hadithWords.any(lower.contains);
  }

  /// Public wrappers for testability.
  static bool possibleQuote(String raw) => _possibleQuote(raw);
  static bool looksLikeHadith(String raw) => _looksLikeHadith(raw);

  // ── API call ─────────────────────────────────────────────────────────────
  static Future<AskAIResponse> ask({
    required String text,
    String lang = 'en',
  }) async {
    if (!isConfigured) {
      return const AskAIResponse(
        verdict: 'refused',
        type: 'general_qna',
        answer: 'ASK Iman AI is not configured yet. Please try again in a little while.',
        errorCode: 'ai_not_configured',
      );
    }

    final raw = text.trim();
    if (raw.isEmpty) {
      return const AskAIResponse(
        verdict: 'refused',
        type: 'general_qna',
        answer: 'Please type a question or paste the text you want to verify.',
        errorCode: 'empty_input',
      );
    }
    if (raw.length > 4000) {
      return const AskAIResponse(
        verdict: 'refused',
        type: 'general_qna',
        answer: 'Please keep your question under 4000 characters.',
        errorCode: 'too_long',
      );
    }

    try {
      // Quota check lives inside the try so ask() can never throw uncaught.
      final quota = await _checkQuota();
      if (quota != null) return quota;

      // 0) Corpus-first short-circuit: quote-like text is verified straight
      //    against the corpus using ZERO Gemini calls. Both outcomes are
      //    cached locally, so repeat checks (verified or unverified) are
      //    instant and cost no Gemini quota either.
      if (_possibleQuote(raw)) {
        final asHadith = _looksLikeHadith(raw);
        final checked = asHadith ? 'hadith_check' : 'quran_check';
        final cached = await _checkCache(checked, raw, lang);
        if (cached != null) return cached;

        List<AskAICitation> refs;
        try {
          refs = asHadith ? await _verifyHadith(raw, lang) : await _verifyQuran(raw, lang);
        } catch (e) {
          // Corpus unavailable (e.g. offline with a cold cache): surface an
          // honest error rather than a false "This is not in my knowledge."
          debugPrint('AI: corpus verify error: $e');
          rethrow;
        }
        if (refs.isEmpty) {
          final response = AskAIResponse(
            verdict: 'unverified',
            type: asHadith ? 'hadith' : 'quran',
            answer: _buildUnverifiedAnswer(asHadith ? 'hadith_check' : 'quran_check', lang),
            lang: lang,
          );
          await _storeCache(checked, raw, lang, response);
          return response;
        }
        final response = AskAIResponse(
          verdict: 'verified',
          type: asHadith ? 'hadith' : 'quran',
          answer: asHadith
              ? _buildVerifiedHadithAnswer(refs)
              : _buildVerifiedAyahAnswer(refs),
          citations: refs,
          lang: lang,
        );
        await _storeCache(checked, raw, lang, response);
        return response;
      }

      // 1) Everything else — questions, greetings, short phrases — is a single
      //    QnA call. The QnA system prompt enforces domain/refusal rules inline,
      //    so the separate intent-classifier round-trip is gone (halves reply
      //    latency and keeps greetings friendly).
      //
      //    Islamic-topic questions with grounded sources use a structured flow:
      //    the model writes ONLY the verdict + general explanation (JSON);
      //    the exact ayah/hadith text + translation is rendered as citation
      //    cards below the answer. Retrieval failures degrade to a plain answer
      //    — never a crash or fabricated source.
      var refs = const <AskAICitation>[];
      try {
        if (looksLikeIslamicTopic(raw)) {
          refs = await _retrieveTopicSources(raw, lang);
        }
      } catch (e) {
        debugPrint('AI: topic-source retrieval failed (plain answer): $e');
      }
      if (refs.isEmpty) {
        // Plain path: no grounded sources attached.
        final user = (lang == 'ur' || lang == 'ps')
            ? '$raw\n\n(Answer in Urdu.)'
            : raw;
        final answer = await _callGemini(system: _qnaSystem, user: user);
        final response = AskAIResponse(
          verdict: 'answer',
          type: 'general_qna',
          answer: answer,
          lang: lang,
        );
        if (response.errorCode == null) await _recordUsage();
        return response;
      }

      // Sourced path: verdict/explanation from the model, citations assembled
      // deterministically from the retrieved corpus data.
      final refsBlock =
          '\n\nVERIFIED REFERENCES (you may only REFERENCE these by their label, '
          'never quote their full text):\n${_referencesBlock(refs)}';
      final user = (lang == 'ur' || lang == 'ps')
          ? '$raw\n\n(Answer in Urdu.)$refsBlock'
          : '$raw$refsBlock';
      var answer = '';
      var parsed = _parseSourcedAnswer(
          await _callGemini(system: _sourcedQnaSystem, user: user));
      if (parsed == null) {
        // Safe fallback: plain model text. The citations are rendered below as
        // cards, so we do NOT echo their text here (avoids repetition).
        answer = await _callGemini(system: _qnaSystem, user: '$raw$refsBlock');
      } else {
        answer = buildSourcedAnswer(
          verdict: parsed.verdict,
          refs: refs,
          explanation: parsed.explanation,
        );
      }
      final response = AskAIResponse(
        verdict: 'answer',
        type: 'general_qna',
        answer: answer,
        citations: refs,
        lang: lang,
      );
      // Only successful answers consume the user-visible quota. Failed/blocked
      // calls (errorCode set) and corpus-only verification cost nothing.
      if (response.errorCode == null) {
        await _recordUsage();
      }
      return response;
    } catch (e, st) {
      debugPrint('AI: ask error: $e\n$st');
      return _fromException(e);
    }
  }

  // ── Gemini HTTP call ─────────────────────────────────────────────────────
  static Future<String> _callGemini({
    required String system,
    required String user,
    double temperature = 0.3,
    int retries = 1,
  }) async {
    final body = {
      'contents': [
        {'role': 'user', 'parts': [{'text': user}]}
      ],
      'systemInstruction': {
        'parts': [{'text': system}]
      },
      'generationConfig': {
        'temperature': temperature,
      },
    };

    for (var attempt = 0; attempt <= retries; attempt++) {
      final res = await http
          .post(
            Uri.parse('$_genBase/$_model:generateContent'),
            headers: {
              'Content-Type': 'application/json',
              'x-goog-api-key': _effectiveApiKey,
            },
            body: jsonEncode(body),
          )
          .timeout(const Duration(seconds: 45));

      if (res.statusCode == 429) {
        // Rate-limited — retrying would only double the hits on an unhappy API.
        throw _GeminiHttpError(429, _readGeminiError(res.body));
      }
      if ((res.statusCode == 502 || res.statusCode == 503) &&
          attempt < retries) {
        await Future<void>.delayed(const Duration(seconds: 5));
        continue;
      }
      if (res.statusCode >= 300) {
        throw _GeminiHttpError(res.statusCode, _readGeminiError(res.body));
      }
      final j = jsonDecode(res.body) as Map<String, dynamic>;
      final candidates = (j['candidates'] as List?) ?? [];
      final parts = (candidates.isNotEmpty &&
              candidates.first is Map &&
              (candidates.first as Map)['content'] is Map)
          ? ((candidates.first as Map)['content'] as Map)['parts'] as List?
          : null;
      final text = ((parts ?? [])
              .map((p) => (p is Map && p['text'] is String) ? p['text'] as String : '')
              .join(''))
          .trim();
      if (text.isEmpty) throw _GeminiHttpError(200, 'Empty AI response');
      return text;
    }
    throw _GeminiHttpError(429, 'Rate limited');
  }

  static String _readGeminiError(String body) {
    try {
      final j = jsonDecode(body) as Map<String, dynamic>;
      final err = j['error'];
      if (err is Map && err['message'] is String) return err['message'] as String;
    } catch (_) {}
    return body;
  }

  static Map<String, dynamic>? _parseJsonObject(String text) {
    try {
      final v = jsonDecode(text);
      if (v is Map) return Map<String, dynamic>.from(v);
    } catch (_) {}
    final m = RegExp(r'\{[\s\S]*\}').firstMatch(text);
    if (m != null) {
      try {
        final v = jsonDecode(m[0]!);
        if (v is Map) return Map<String, dynamic>.from(v);
      } catch (_) {}
    }
    return null;
  }

  // ── Corpus caches (memory + disk, 14-day TTL) ────────────────────────────
  static final Map<String, _CorpusEntry> _corpusCache = {};
  static const int _corpusTtlMs = 14 * 24 * 3600 * 1000;

  static Future<Directory> _corpusDir() async {
    final base = await getApplicationSupportDirectory();
    final dir = Directory('${base.path}/ai_corpus');
    if (!await dir.exists()) await dir.create(recursive: true);
    return dir;
  }

  static Future<List<Map<String, dynamic>>?> _readDiskCache(String key) async {
    try {
      final f = File('${(await _corpusDir()).path}/$key.json');
      if (!await f.exists()) return null;
      final stat = await f.stat();
      if (DateTime.now().difference(stat.modified).inMilliseconds >= _corpusTtlMs) {
        await f.delete();
        return null;
      }
      final list = jsonDecode(await f.readAsString()) as List;
      return list.whereType<Map>().map((e) => Map<String, dynamic>.from(e)).toList();
    } catch (e) {
      debugPrint('AI: disk cache read failed ($key): $e');
      return null;
    }
  }

  static Future<void> _writeDiskCache(String key, List<Map<String, dynamic>> items) async {
    try {
      final f = File('${(await _corpusDir()).path}/$key.json');
      await f.writeAsString(jsonEncode(items), flush: true);
    } catch (e) {
      debugPrint('AI: disk cache write failed ($key): $e');
    }
  }

  static Future<dynamic> _fetchJson(String url, String cacheKey) async {
    final now = DateTime.now().millisecondsSinceEpoch;
    final hit = _corpusCache[cacheKey];
    if (hit != null && now - hit.t < _corpusTtlMs) return hit.data;

    final res = await http
        .get(Uri.parse(url))
        .timeout(const Duration(seconds: 45));
    if (res.statusCode != 200) {
      throw StateError('Corpus fetch failed ${res.statusCode} $url');
    }
    final data = jsonDecode(utf8.decode(res.bodyBytes));
    _corpusCache[cacheKey] = _CorpusEntry(now, data);
    return data;
  }

  static Future<List<Map<String, dynamic>>> _loadQuran(String edition) async {
    final key = 'quran_parsed_$edition';
    final hit = _corpusCache[key];
    if (hit != null && DateTime.now().millisecondsSinceEpoch - hit.t < _corpusTtlMs) {
      return List<Map<String, dynamic>>.from(hit.data);
    }

    final fromDisk = await _readDiskCache(key);
    if (fromDisk != null && fromDisk.isNotEmpty) {
      _corpusCache[key] = _CorpusEntry(DateTime.now().millisecondsSinceEpoch, fromDisk);
      return List<Map<String, dynamic>>.from(fromDisk);
    }

    final url = 'https://api.alquran.cloud/v1/quran/${_quranEditions[edition]}';
    final raw = await _fetchJson(url, 'quran_raw_$edition');
    final surahs = (raw['data'] as Map)['surahs'] as List;
    final items = <Map<String, dynamic>>[];
    for (final s in surahs) {
      final ayahs = (s as Map)['ayahs'] as List? ?? const [];
      for (final a in ayahs) {
        final am = a as Map;
        items.add({
          'number': am['number'],
          'numberInSurah': am['numberInSurah'],
          'text': am['text'],
          'surah': {
            'number': s['number'],
            'name': s['name'],
            'englishName': s['englishName'],
            'meaning': s['englishNameTranslation'] ?? '',
          },
        });
      }
    }
    _corpusCache[key] = _CorpusEntry(DateTime.now().millisecondsSinceEpoch, items);
    unawaited(_writeDiskCache(key, items));
    return items;
  }

  static Future<List<Map<String, dynamic>>> _loadHadith(String bookSlug, String lang) async {
    final key = 'hadith_parsed_${lang}_$bookSlug';
    final hit = _corpusCache[key];
    if (hit != null && DateTime.now().millisecondsSinceEpoch - hit.t < _corpusTtlMs) {
      return List<Map<String, dynamic>>.from(hit.data);
    }

    final fromDisk = await _readDiskCache(key);
    if (fromDisk != null && fromDisk.isNotEmpty) {
      _corpusCache[key] = _CorpusEntry(DateTime.now().millisecondsSinceEpoch, fromDisk);
      return List<Map<String, dynamic>>.from(fromDisk);
    }

    final url =
        'https://cdn.jsdelivr.net/gh/fawazahmed0/hadith-api@1/editions/$lang-$bookSlug.json';
    final raw = await _fetchJson(url, 'hadith_raw_${lang}_$bookSlug');
    final hadiths = ((raw['hadiths'] as List?) ?? const []);
    final items = <Map<String, dynamic>>[];
    for (final h in hadiths) {
      final hm = h as Map;
      final grades = hm['grades'] as List? ?? const [];
      items.add({
        'hadithnumber': hm['hadithnumber'] as int?,
        'arabicnumber': hm['arabicnumber'],
        'text': hm['text'] ?? '',
        'grade': (grades.isNotEmpty && grades.first is Map)
            ? (grades.first as Map)['grade'] ?? ''
            : '',
        'reference': hm['reference'],
      });
    }
    _corpusCache[key] = _CorpusEntry(DateTime.now().millisecondsSinceEpoch, items);
    unawaited(_writeDiskCache(key, items));
    return items;
  }

  /// Pre-warms the most common corpus loads so the first verification in the
  /// session is instant. Failures are swallowed (loads happen on demand).
  static Future<void> prewarmCorpus() async {
    try {
      await Future.wait([
        _loadQuran('ara'),
        _loadQuran('eng'),
      ]);
      debugPrint('AI: corpus prewarm complete.');
    } catch (e) {
      debugPrint('AI: corpus prewarm failed (will load on demand): $e');
    }
  }

  // ── Verification (grounded) ──────────────────────────────────────────────

  static ({bool ok}) _matchAyahText(
    Map<String, dynamic> it,
    Map<int, Map<String, dynamic>> trans,
    String input,
    bool arabic,
  ) {
    final texts = <String>[];
    final ar = it['text'];
    if (ar is String && ar.isNotEmpty) texts.add(ar);
    final tr = trans[it['number']];
    if (tr != null && tr['text'] is String && (tr['text'] as String).isNotEmpty) {
      texts.add(tr['text'] as String);
    }
    var best = 0.0;
    var bestC = 0.0;
    for (final tx in texts) {
      final r = rankMatch(hayText: tx, needleText: input);
      if (r.score > best) {
        best = r.score;
        bestC = r.containment;
      }
    }
    return arabic
        ? (ok: best >= _arStrictScore && bestC >= _arStrictContainment)
        : (ok: best >= _latinStrictScore && bestC >= _latinStrictContainment);
  }

  static AskAICitation _ayahCitation(
      Map<String, dynamic> it, Map<int, Map<String, dynamic>> trans) {
    final surah = it['surah'] as Map;
    final tr = trans[it['number']];
    return AskAICitation(
      kind: 'ayah',
      book: 'Quran',
      surahNumber: surah['number'] as int?,
      surahName: surah['englishName'] as String?,
      surahArabic: surah['name'] as String?,
      ayahNumber: it['numberInSurah'] as int?,
      arabic: it['text'] ?? '',
      text: (tr != null && tr['text'] is String) ? tr['text'] as String : '',
    );
  }

  static Future<List<AskAICitation>> _verifyQuran(String input, String lang) async {
    final [araItems, engItems] = await Future.wait([
      _loadQuran('ara'),
      _loadQuran('eng'),
    ]);
    final urdItems = (lang == 'ur' || lang == 'ps')
        ? await _loadQuran('urd')
        : <Map<String, dynamic>>[];
    final byEng = <int, Map<String, dynamic>>{for (final i in engItems) i['number'] as int: i};
    final byUrd = <int, Map<String, dynamic>>{for (final i in urdItems) i['number'] as int: i};
    final trans = byUrd.isNotEmpty ? byUrd : byEng;
    final arabic = isArabicScript(input);
    final idx = surahNameIndex(araItems);

    // 1) Pinned claim: verify ONLY the location the user named.
    final claim = parseQuranClaim(input, idx);
    if (claim != null) {
      for (final it in araItems) {
        if (it['surah']['number'] == claim.$1 && it['numberInSurah'] == claim.$2) {
          if (_matchAyahText(it, trans, input, arabic).ok) {
            return [_ayahCitation(it, trans)];
          }
          return const [];
        }
      }
      return const [];
    }

    // 2) Whole-corpus strict search; greedy ties are refused, and only a
    //    clear-winner hit is verified without model help.
    if (arabic) {
      final hits = findMatches(araItems,
          textOf: (i) => i['text'], needleText: input, minScore: _arMinScore, limit: 5);
      final acc = strictAccept(hits,
          strictScore: _arStrictScore,
          strictContainment: _arStrictContainment,
          gap: _arStrictGap);
      if (acc.ok) {
        return [_ayahCitation(acc.best!.item, trans)];
      }
      final bandCands = <AskAICitation>[];
      for (final h in hits) {
        if (h.score >= _arAdjudicateMin) bandCands.add(_ayahCitation(h.item, trans));
        if (bandCands.length >= 3) break;
      }
      return bandCands.isNotEmpty ? _adjudicate(input, bandCands) : const [];
    }

    final hits = findMatches(engItems,
        textOf: (i) => i['text'], needleText: input, minScore: _latinMinScore, limit: 5);
    final acc = strictAccept(hits,
        strictScore: _latinStrictScore,
        strictContainment: _latinStrictContainment,
        gap: _latinStrictGap);
    if (acc.ok) {
      return [_ayahCitation(acc.best!.item, trans)];
    }
    final bandCands = <AskAICitation>[];
    for (final h in hits) {
      if (h.score >= _latinAdjudicateMin) bandCands.add(_ayahCitation(h.item, trans));
      if (bandCands.length >= 3) break;
    }
    if (bandCands.isNotEmpty) return _adjudicate(input, bandCands);

    // Urdu fallback only when English produced nothing at all.
    if (urdItems.isNotEmpty) {
      final uhits = findMatches(urdItems,
          textOf: (i) => i['text'], needleText: input, minScore: _latinMinScore, limit: 5);
      final uacc = strictAccept(uhits,
          strictScore: _latinStrictScore,
          strictContainment: _latinStrictContainment,
          gap: _latinStrictGap);
      if (uacc.ok) {
        return [_ayahCitation(uacc.best!.item, trans)];
      }
    }
    return const [];
  }

  static List<AskAICitation> _hadithRefsFrom(List<Map<String, dynamic>> entries) {
    final sorted = List<Map<String, dynamic>>.from(entries)
      ..sort((a, b) => (b['score'] as double).compareTo(a['score'] as double));
    final out = <AskAICitation>[];
    final seen = <String>{};
    for (final e in sorted) {
      final k = '${e['slug']}|${e['hadithNumber']}';
      if (seen.contains(k)) continue;
      seen.add(k);
      out.add(AskAICitation(
        kind: 'hadith',
        book: e['book'] as String,
        hadithNumber: e['hadithNumber'] as int?,
        arabic: (e['arabic'] as String?) ?? '',
        text: (e['text'] as String?) ?? '',
        grade: (e['grade'] as String?) ?? '',
      ));
    }
    return out;
  }

  static Future<List<AskAICitation>> _verifyHadith(String input, String lang) async {
    final arabic = isArabicScript(input);

    // 1) Pinned claim: verify ONLY the book+number the user named.
    final claim = parseHadithClaim(input);
    if (claim != null && claim.$2 != null) {
      final slug = claim.$1;
      final bookName = hadithBooks.firstWhere((b) => b['slug'] == slug)['name'] as String;
      final [eng, ara] = await Future.wait([
        _loadHadith(slug, 'eng'),
        _loadHadith(slug, 'ara'),
      ]);
      Map<String, dynamic>? target;
      for (final h in eng) {
        if (h['hadithnumber'] == claim.$2) {
          target = h;
          break;
        }
      }
      if (target == null) return const [];
      final r = rankMatch(hayText: target['text'] ?? '', needleText: input);
      final ok = arabic
          ? r.score >= _arStrictScore && r.containment >= _arStrictContainment
          : r.score >= _latinStrictScore && r.containment >= _latinStrictContainment;
      if (!ok) return const [];
      Map<String, dynamic>? araTarget;
      for (final h in ara) {
        if (h['hadithnumber'] == claim.$2) {
          araTarget = h;
          break;
        }
      }
      return [
        AskAICitation(
          kind: 'hadith',
          book: bookName,
          hadithNumber: claim.$2,
          arabic: (araTarget?['text'] as String?) ?? '',
          text: target['text'] ?? '',
          grade: (target['grade'] as String?) ?? '',
        )
      ];
    }

    // 2) Whole-corpus strict / adjudicated search.
    final jobs = hadithBooks.map((book) async {
      try {
        final [eng, ara] = await Future.wait([
          _loadHadith(book['slug']!, 'eng'),
          _loadHadith(book['slug']!, 'ara'),
        ]);
        final byNumber = <int, Map<String, dynamic>>{
          for (final h in ara)
            if (h['hadithnumber'] is int) h['hadithnumber'] as int: h
        };

        final hits = arabic
            ? findMatches(ara, textOf: (i) => i['text'], needleText: input, minScore: _arMinScore, limit: 3)
            : findMatches(eng, textOf: (i) => i['text'], needleText: input, minScore: _latinMinScore, limit: 3);
        if (hits.isEmpty) return const <Map<String, dynamic>>[];
        final best = hits.first;
        final num = best.item['hadithnumber'] as int?;
        final araHadith = num != null ? byNumber[num] : null;
        return [
          {
            'slug': book['slug'],
            'book': book['name'],
            'hadithNumber': num,
            'arabic': (araHadith?['text'] as String?) ?? '',
            'text': best.item['text'] ?? '',
            'grade': (best.item['grade'] as String?) ?? '',
            'score': best.score,
            'containment': best.containment,
          }
        ];
      } catch (_) {
        // Skip a book that fails to load (404 / network / parse) instead of
        // aborting the whole-corpus verification.
        return const <Map<String, dynamic>>[];
      }
    });
    final entries = (await Future.wait(jobs)).expand((x) => x).toList();
    entries.sort((a, b) => (b['score'] as double).compareTo(a['score'] as double));
    if (entries.isEmpty) return const [];

    String keyOf(Map e) {
      final t = normalizeForMatch((e['text'] as String?) ?? '');
      return t.length <= 48 ? t : t.substring(0, 48);
    }

    final strictScoreBar = arabic ? _arStrictScore : _latinStrictScore;
    final strictContBar = arabic ? _arStrictContainment : _latinStrictContainment;
    final adjudicateMin = arabic ? _arAdjudicateMin : _latinAdjudicateMin;

    final strictGroups = <String, List<Map<String, dynamic>>>{};
    for (final e in entries) {
      if ((e['score'] as double) >= strictScoreBar &&
          (e['containment'] as double) >= strictContBar) {
        final k = keyOf(e);
        (strictGroups[k] ??= []).add(e);
      }
    }
    if (strictGroups.length == 1) {
      final refs = _hadithRefsFrom(strictGroups.entries.first.value);
      if (refs.isNotEmpty) return refs;
    }

    final bandCands = <AskAICitation>[];
    final seenN = <String>{};
    for (final e in entries) {
      if ((e['score'] as double) < adjudicateMin) continue;
      final k = keyOf(e);
      if (seenN.add(k)) {
        bandCands.add(_hadithRefsFrom([e]).first);
        if (bandCands.length >= 3) break;
      }
    }
    return bandCands.isNotEmpty ? _adjudicate(input, bandCands) : const [];
  }

  // ── Grounded adjudicator (near-miss paraphrases/translations) ───────────
  // One Gemini call that REVISES ONLY the corpus shortlist already found. The
  // model may pick one listed passage or refuse; it can never propose a source
  // that is not grounded in the provided passages.

  static const String _adjudicateSystem =
      'You are an extremely cautious Islamic reference verification adjudicator.\n'
      'You are given a user message (a religious quotation, or a translation of one) and a short\n'
      'numbered list of passages drawn ONLY from a verified Quran/hadith corpus.\n'
      'Rules:\n'
      '- Decide whether the message is a faithful rendering (verbatim, or a close translation/paraphrase)\n'
      '  of EXACTLY ONE of the listed passages.\n'
      '- Reply with ONLY JSON: {"match": true or false, "index": the passage number or null, "reason": "one short sentence"}.\n'
      '- match MUST be false if: the message matches NONE of the passages, it could match MORE THAN ONE,\n'
      '  or you are the least bit unsure.\n'
      '- You are FORBIDDEN from naming, recalling, searching, or inventing any surah, ayah number, hadith\n'
      '  book, or passage that is not in the list. Never guess a source.\n'
      '- Accuracy is life-critical: when in doubt, answer false.';

  static String _clip(String s) => s.length <= 600 ? s : s.substring(0, 600);

  static Future<List<AskAICitation>> _adjudicate(
      String input, List<AskAICitation> candidates) async {
    final shortlist = candidates.take(3).toList();
    final buf = StringBuffer('USER MESSAGE: $input\n\nPASSAGES:\n');
    for (var i = 0; i < shortlist.length; i++) {
      final c = shortlist[i];
      final label = c.kind == 'ayah'
          ? 'surah ${c.surahName} (${c.surahArabic}) ${c.surahNumber}:${c.ayahNumber}'
          : (c.hadithNumber != null ? '${c.book} #${c.hadithNumber}' : c.book);
      final body = [c.arabic, c.text].where((s) => s.isNotEmpty).join(' — ');
      buf.writeln('[$i] $label: ${_clip(body)}');
    }
    final res = await _callGemini(
      system: _adjudicateSystem,
      user: buf.toString(),
      temperature: 0.0,
    );
    final j = _parseJsonObject(res);
    if (j == null || j['match'] != true) return const [];
    final index = j['index'];
    if (index is int && index >= 0 && index < shortlist.length) {
      return [shortlist[index]];
    }
    return const [];
  }

  // ── Topic-based source retrieval (general Q&A enrichment) ─────────────────
  // Sources shown are ONLY corpus passages found by deterministic retrieval —
  // the model never generates them. Retrieval failures degrade to a plain
  // (source-less) answer; they never produce an error or a fabricated source.

  static final Map<String, Map<String, List<int>>> _termIndexCache = {};

  static Map<String, List<int>> _termIndexFor(
      List<Map<String, dynamic>> items, String field, String key) {
    final hit = _termIndexCache[key];
    if (hit != null) return hit;
    final idx = buildTermIndex([for (final i in items) (i[field] as String? ?? '')]);
    _termIndexCache[key] = idx;
    return idx;
  }

  static Future<({AskAICitation c, int matched})?> _hadithTopicBest(
      Map<String, String> book, List<String> terms) async {
    final slug = book['slug']!;
    final [eng, ara] = await Future.wait([
      _loadHadith(slug, 'eng'),
      _loadHadith(slug, 'ara'),
    ]);
    final idx = _termIndexFor(eng, 'text', 'hadith_eng_$slug');
    final ranked = topicRank(idx, eng.length, terms);
    if (ranked.isEmpty) return null;
    final best = ranked.first;
    final h = eng[best.index];
    final num = h['hadithnumber'] as int?;
    String? araText;
    if (num != null) {
      for (final a in ara) {
        if (a['hadithnumber'] == num) {
          araText = a['text'] as String?;
          break;
        }
      }
    }
    // Fallback: ara and eng files are parallel arrays — use the same position
    // so the Arabic is still shown even when the number lookup misses.
    if ((araText == null || araText.isEmpty) && best.index < ara.length) {
      araText = ara[best.index]['text'] as String?;
    }
    return (
      c: AskAICitation(
        kind: 'hadith',
        book: book['name'] as String,
        hadithNumber: num,
        arabic: araText ?? '',
        text: (h['text'] as String?) ?? '',
        grade: (h['grade'] as String?) ?? '',
      ),
      matched: best.matchedTerms,
    );
  }

  static Future<List<AskAICitation>> _retrieveTopicSources(
      String input, String lang) async {
    final terms = topicQueryTerms(input);
    if (terms.isEmpty) return const [];
    final urdu = lang == 'ur' || lang == 'ps';

    final [araItems, engItems] = await Future.wait([
      _loadQuran('ara'),
      _loadQuran('eng'),
    ]);
    final urdItems =
        urdu ? await _loadQuran('urd') : const <Map<String, dynamic>>[];
    final byAra = <int, Map<String, dynamic>>{
      for (final i in araItems) i['number'] as int: i,
    };
    final byEng = <int, String>{
      for (final i in engItems) i['number'] as int: i['text'] as String,
    };
    final byUrd = <int, String>{
      for (final i in urdItems) i['number'] as int: i['text'] as String,
    };

    // 2 ayahs: ranked by idf-weighted term overlap.
    final quIdx = _termIndexFor(engItems, 'text', 'quran_eng');
    final qRanked = topicRank(quIdx, engItems.length, terms).take(2).toList();
    final ayahs = <({AskAICitation c, int matched})>[];
    for (final h in qRanked) {
      final num = engItems[h.index]['number'] as int;
      final ara = byAra[num];
      if (ara == null) continue;
      final e = byEng[num] ?? '';
      final u = byUrd[num] ?? '';
      final text =
          !urdu ? e : (u.isNotEmpty ? '$e\n\nاردو ترجمہ: $u' : e);
      ayahs.add((
        c: AskAICitation(
          kind: 'ayah',
          book: 'Quran',
          surahNumber: ara['surah']['number'] as int?,
          surahName: ara['surah']['englishName'] as String?,
          surahArabic: ara['surah']['name'] as String?,
          ayahNumber: ara['numberInSurah'] as int?,
          arabic: ara['text'] ?? '',
          text: text,
        ),
        matched: h.matchedTerms,
      ));
    }

    // 2 hadith: best narration per book, global top 2 by matched-term count.
    final hadiths = <({AskAICitation c, int matched})>[];
    for (final book in hadithBooks) {
      try {
        final best = await _hadithTopicBest(book, terms);
        if (best != null) hadiths.add(best);
      } catch (_) {
        // A single failing book (404 / network / parse) must not blank out
        // the sources for the rest of the corpus — skip it and continue.
      }
    }
    hadiths.sort((a, b) => b.matched.compareTo(a.matched));

    final refs = [
      ...ayahs.map((e) => e.c),
      ...hadiths.take(2).map((e) => e.c),
    ];
    if (refs.isEmpty) return const [];

    // Evidence confidence: a single generic content-word hit (e.g. "people")
    // is NOT enough to attach sources — otherwise almost every question would
    // show 4 cards. Require an anchor term or >=2 distinct matched terms.
    final allMatched = [...ayahs, ...hadiths].map((e) => e.matched);
    if (!topicEvidenceConfident(terms, allMatched)) return const [];

    // Ambiguity guard: one grounded Gemini call (model may only KEEP listed
    // passages, never add) only when the lexical evidence is weak/conflicting.
    final clear = allMatched.any((m) => m >= 2) || terms.length >= 4;
    if (refs.length <= 1 || clear) return refs;
    try {
      return await _guardRelevance(input, refs);
    } catch (e) {
      // The relevance guard is advisory only — never let it wipe out real,
      // corpus-grounded sources on a hiccup.
      debugPrint('AI: relevance guard failed — keeping sources: $e');
      return refs;
    }
  }

  static const String _relevanceSystem =
      'You are a meticulous Islamic content relevance filter.\n'
      'Given a user question and a numbered list of REAL Quran ayahs / hadith passages, '
      'decide which listed passages genuinely help answer the question.\n'
      'Reply with ONLY JSON: {"keep": [array of 1-based passage numbers], "reason": "one short sentence"}.\n'
      'Rules:\n'
      '- Keep a passage ONLY if it is clearly relevant to the question topic.\n'
      '- You are FORBIDDEN from adding, recalling, or inventing any passage that is not in the list.\n'
      '- An empty array is fine.\n'
      '- Accuracy is life-critical: when in doubt, do NOT keep the passage.';

  static Future<List<AskAICitation>> _guardRelevance(
      String question, List<AskAICitation> candidates) async {
    final shortlist = candidates.take(6).toList();
    if (shortlist.length < 2) return shortlist;
    final buf = StringBuffer('USER QUESTION: $question\n\nPASSAGES:\n');
    for (var i = 0; i < shortlist.length; i++) {
      final c = shortlist[i];
      final label = c.kind == 'ayah'
          ? 'Quran ${c.surahName} ${c.surahNumber}:${c.ayahNumber}'
          : (c.hadithNumber != null ? '${c.book} #${c.hadithNumber}' : c.book);
      final body = [c.arabic, c.text].where((s) => s.isNotEmpty).join(' — ');
      buf.writeln('[${i + 1}] $label: ${_clip(body)}');
    }
    final res = await _callGemini(
      system: _relevanceSystem,
      user: buf.toString(),
      temperature: 0.0,
    );
    final j = _parseJsonObject(res);
    if (j == null) return shortlist;
    final keep = j['keep'];
    if (keep is! List) return shortlist;
    final idxs = keep
        .whereType<num>()
        .map((x) => x.toInt() - 1)
        .where((i) => i >= 0 && i < shortlist.length)
        .toSet();
    if (idxs.isEmpty) return shortlist;
    return [
      for (var i = 0; i < shortlist.length; i++)
        if (idxs.contains(i)) shortlist[i],
    ];
  }

  /// The "VERIFIED REFERENCES" block injected into the QnA prompt: the ONLY
  /// sources the model is allowed to quote, and always attached as citations.
  static String _referencesBlock(List<AskAICitation> refs) {
    final buf = StringBuffer();
    for (var i = 0; i < refs.length; i++) {
      final c = refs[i];
      final label = c.kind == 'ayah'
          ? 'Surah ${c.surahName} ${c.surahNumber}:${c.ayahNumber}'
          : (c.hadithNumber != null ? '${c.book} #${c.hadithNumber}' : c.book);
      buf.writeln('[${i + 1}] $label');
      if (c.arabic.isNotEmpty) buf.writeln('Arabic: ${c.arabic}');
      buf.writeln('Translation: ${c.text}');
      buf.writeln('');
    }
    return buf.toString().trim();
  }

  // ── Human-readable answers built ONLY from retrieved data ───────────────
  static String _buildVerifiedAyahAnswer(List<AskAICitation> refs) {
    final r = refs.first;
    final header =
        'Yes — this is from the Quran. It is Surah ${r.surahName} (${r.surahArabic}), '
        'Ayah ${r.ayahNumber} (${r.surahNumber}:${r.ayahNumber}).';
    final lines = <String>[header, r.arabic];
    if (r.text.isNotEmpty) lines.add('Translation: ${r.text}');
    lines.add('The Quran is the preserved word of Allah, authentic in its entirety.');
    return lines.join('\n\n');
  }

  static String _buildVerifiedHadithAnswer(List<AskAICitation> refs) {
    final r = refs.first;
    final loc = r.hadithNumber != null ? 'Hadith ${r.hadithNumber}' : '';
    final header = 'Yes — this is a recorded narration. It appears in $r.book, $loc.'
        .replaceAll(' ,', ',')
        .replaceAll(' .', '.');
    final lines = <String>[header.trim()];
    if (r.arabic.isNotEmpty) lines.add(r.arabic);
    lines.add(r.text);
    if (r.grade != null && r.grade!.isNotEmpty) {
      lines.add('Authenticity note: ${r.grade}');
    }
    if (refs.length > 1) {
      final also = refs.skip(1)
          .map((x) => x.hadithNumber != null ? '${x.book} Hadith ${x.hadithNumber}' : x.book)
          .join(', ');
      lines.add('It is also recorded in: $also.');
    }
    return lines.join('\n\n');
  }

  static String _buildUnverifiedAnswer(String type, String lang) {
    // Spec (lib/changes.txt): uncertainty must be stated strictly as
    // "This is not in my knowledge." — no guessing, no extrapolating.
    final urdu = lang == 'ur' || lang == 'ps';
    if (type == 'quran_check') {
      if (urdu) {
        return 'یہ میرے علم میں نہیں ہے۔\n\n'
            'میں نے اس کا قرآنِ کریم کے مکمل متن سے مقابلہ کیا ہے اور اسے وہاں نہیں پایا، '
            'اور میں اندازہ نہیں لگاتا۔ براہِ کرم پوری آیت (عربی متن کے ساتھ) دیجیے، '
            'یا کسی مستند مصحف یا قاری / عالم سے تصدیق کروائیے۔';
      }
      return 'This is not in my knowledge.\n\n'
          'I cross-checked this text against the full Quran and did not find it there, '
          'and I do not guess. Please share the full ayah (Arabic text preferred), '
          'or verify it with a reliable mushaf or a knowledgeable reciter.';
    }
    if (urdu) {
      return 'یہ میرے علم میں نہیں ہے۔\n\n'
          'میں نے اس کا قرآنِ کریم اور چھ کتبِ حدیث کے مکمل متن سے مقابلہ کیا ہے '
          'اور اسے کہیں نہیں پایا، اور میں اندازہ نہیں لگاتا۔ '
          'براہِ کرم اسے کسی مستند ذریعے یا عالم سے تصدیق کروائیے۔';
    }
    return 'This is not in my knowledge.\n\n'
        'I cross-checked this text against the Quran and the six major hadith '
        'collections and could not find it there, and I do not guess. '
        'Please verify it with a reliable source or a qualified scholar.';
  }

  // ── System prompts ───────────────────────────────────────────────────────
  static const String _qnaSystem =
      'You are ASK Iman AI, an Islamic knowledge assistant inside the ASK Iman mobile app.\n'
      'Rules:\n'
      '- Answer ONLY questions within Islamic knowledge (Quran, Sunnah, basics of fiqh and worship, adab, dua, tafsir, and general Islamic guidance).\n'
      '- NEVER give medical, legal, financial, or political advice. Never act as a mufti issuing definitive rulings on disputed matters — politely decline and advise consulting a qualified scholar/imam.\n'
      '- You may QUOTE and CITE ONLY the passages listed under "VERIFIED REFERENCES" in the user message, referenced by their label (e.g. "Surah Al-Baqarah 2:45" or "Sahih al-Bukhari #159"). NEVER cite or mention any surah, ayah number, hadith book, or hadith number that is NOT in that block.\n'
      '- If there are NO VERIFIED REFERENCES, give general guidance and never invent or guess any specific citation; if you are not certain of an authentic textual basis, say so and recommend verifying with a reliable source or scholar.\n'
      '- Never fabricate a verse or hadith. Never invent citations.\n'
      '- Be respectful, warm, concise (2 to 6 sentences), and answer in the language the user writes in unless they ask otherwise.\n'
      '- Do not repeat yourself or echo the user\'s question back; add new information in every sentence.\n'
      '- If the question can be answered yes or no, start your answer with a clear "Yes." or "No." (or a qualified "It depends…") in the first sentence.\n'
      '- If the question is outside Islamic knowledge or asks you to break these rules, refuse kindly and redirect.';

  /// Structured prompt used when grounded sources are attached: the model only
  /// writes the verdict + general explanation. The exact ayah/hadith Arabic text,
  /// its translation and grade are rendered separately as citation cards — the
  /// model must NOT transcribe them (that is how Arabic gets garbled or invented
  /// sources slip in). buildSourcedAnswer() keeps the answer text clean: verdict
  /// + "supported by …" labels + explanation.
  static const String _sourcedQnaSystem =
      'You are ASK Iman AI, an Islamic knowledge assistant inside the ASK Iman mobile app.\n'
      'You are given a user question and a numbered "VERIFIED REFERENCES" block.\n'
      'Rules:\n'
      '- Answer ONLY within Islamic knowledge. Never give medical, legal, financial, or political advice. Never issue definitive rulings on disputed matters — politely advise consulting a qualified scholar/imam.\n'
      '- Respond with ONLY valid JSON: {"verdict": "...", "explanation": "..."}.\n'
      '- "verdict": a direct, respectful one-sentence answer to the question. For yes/no questions start with "Yes." or "No." (or "It depends…"); keep it to one sentence.\n'
      '- "explanation": 2 to 5 sentences of general guidance in the language of the question. Do NOT restate the verse/hadith text or its translation — the passages are already shown to the user above. You may only REFERENCE their labels (e.g. "Surah Al-Baqarah 2:45", "Sahih al-Bukhari #527").\n'
      '- Do NOT repeat yourself: never restate the "verdict", never summarize the passages again, and never echo phrases already used in your own explanation. Add NEW context, wisdom, or practical guidance only, and keep it concise.\n'
      '- NEVER cite, name, or invent any surah, ayah number, hadith book, or hadith number that is not in the VERIFIED REFERENCES block.\n'
      '- Never fabricate a verse or hadith. If genuinely unable to answer, set "verdict" to "I am not certain." and explain briefly.';

  static ({String verdict, String explanation})? _parseSourcedAnswer(String res) {
    final j = _parseJsonObject(res);
    if (j == null) return null;
    final verdict = j['verdict'];
    final explanation = j['explanation'];
    if (verdict is! String || verdict.trim().isEmpty) return null;
    return (
      verdict: verdict.trim(),
      explanation: explanation is String ? explanation.trim() : '',
    );
  }

  // ── Local quota (device-side; mimics the Cloud Function policy) ──────────
  static const String _qDayKey = 'ai_quota_day_v1';
  static const String _qDayDate = 'ai_quota_day_date_v1';
  static const String _qMinKey = 'ai_quota_min_v1';
  static const String _qMinWindow = 'ai_quota_min_window_v1';

  static Future<AskAIResponse?> _checkQuota() async {
    final prefs = await SharedPreferences.getInstance();
    final now = DateTime.now();
    final dateStr = now.toIso8601String().substring(0, 10);
    final minWindow = '${now.toIso8601String().substring(0, 13)}:${now.minute ~/ 5}';

    final lastDate = prefs.getString(_qDayDate) ?? '';
    final dayCount = lastDate == dateStr ? (prefs.getInt(_qDayKey) ?? 0) : 0;

    final lastMin = prefs.getString(_qMinWindow) ?? '';
    final minCount = lastMin == minWindow ? (prefs.getInt(_qMinKey) ?? 0) : 0;

    if (dayCount >= kDayLimit) {
      return const AskAIResponse(
        verdict: 'refused',
        type: 'out_of_scope',
        answer: 'You have reached today\'s 30-question limit. JazakAllah Khair — please come back tomorrow.',
        errorCode: 'daily_limit',
      );
    }
    if (minCount >= kMinuteLimit) {
      return const AskAIResponse(
        verdict: 'refused',
        type: 'out_of_scope',
        answer: 'Please slow down a little. Take a pause between questions.',
        errorCode: 'rate_limited',
      );
    }
    return null;
  }

  // Counts usage only after a successful answer, so failed attempts (503/429,
  // network errors) never burn the user's daily/5-minute budget.
  static Future<void> _recordUsage() async {
    final prefs = await SharedPreferences.getInstance();
    final now = DateTime.now();
    final dateStr = now.toIso8601String().substring(0, 10);
    final minWindow = '${now.toIso8601String().substring(0, 13)}:${now.minute ~/ 5}';

    final lastDate = prefs.getString(_qDayDate) ?? '';
    final dayCount = (lastDate == dateStr ? (prefs.getInt(_qDayKey) ?? 0) : 0) + 1;
    final lastMin = prefs.getString(_qMinWindow) ?? '';
    final minCount = (lastMin == minWindow ? (prefs.getInt(_qMinKey) ?? 0) : 0) + 1;

    await prefs.setString(_qDayDate, dateStr);
    await prefs.setInt(_qDayKey, dayCount);
    await prefs.setString(_qMinWindow, minWindow);
    await prefs.setInt(_qMinKey, minCount);
  }

  // ── Negative-cache: verified/unverified verdicts keyed by normalized hash ─
  static const String _cacheKey = 'ai_verify_cache_v2';
  static final HashMap<String, AskAIResponse> _memoryCache = HashMap();

  static String _claimHash(String intent, String text) {
    final n = normalizeForMatch(text);
    return '$intent|${_simpleHash(n)}';
  }

  static String _simpleHash(String input) {
    var h = 0;
    for (final c in input.codeUnits) {
      h = (h * 31 + c) & 0x7fffffff;
    }
    return h.toRadixString(16);
  }

  static Future<AskAIResponse?> _checkCache(String intent, String text, String lang) async {
    final key = _claimHash(intent, text);
    final mem = _memoryCache[key];
    if (mem != null && mem.lang == lang) return mem;

    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_cacheKey);
    if (raw == null) return null;
    try {
      final map = jsonDecode(raw) as Map<String, dynamic>;
      if (map[key] is Map) {
        final resp = AskAIResponse.fromJson(Map<String, dynamic>.from(map[key] as Map));
        if (resp.lang == lang) {
          _memoryCache[key] = resp;
          return resp;
        }
      }
    } catch (_) {}
    return null;
  }

  static Future<void> _storeCache(String intent, String text, String lang, AskAIResponse resp) async {
    final key = _claimHash(intent, text);
    _memoryCache[key] = resp;

    final prefs = await SharedPreferences.getInstance();
    var map = <String, dynamic>{};
    final raw = prefs.getString(_cacheKey);
    if (raw != null) {
      try {
        map = jsonDecode(raw) as Map<String, dynamic>;
      } catch (_) {}
    }
    map[key] = resp.toJson();
    // Keep the store bounded (~200 entries) to avoid unbounded growth.
    if (map.length > 200) {
      final entries = map.entries.skip(map.length - 200);
      map = <String, dynamic>{for (final e in entries) e.key: e.value};
    }
    await prefs.setString(_cacheKey, jsonEncode(map));
  }

  // ── Error mapping ────────────────────────────────────────────────────────
  static AskAIResponse _fromException(Object e) {
    if (e is _GeminiHttpError) {
      debugPrint('AI: Gemini HTTP ${e.status}: ${e.message}');
      switch (e.status) {
        case 429:
          return const AskAIResponse(
            verdict: 'refused',
            type: 'general_qna',
            answer: 'Too many AI requests right now. Please wait a moment and try again.',
            errorCode: 'rate_limited',
          );
        case 404:
          return const AskAIResponse(
            verdict: 'refused',
            type: 'general_qna',
            answer: 'The AI model is not available in this version of the app. Please update the app and try again.',
            errorCode: 'ai_model_unavailable',
          );
        case 502:
        case 503:
          return const AskAIResponse(
            verdict: 'refused',
            type: 'general_qna',
            answer: 'The AI service is temporarily busy. Please try again in a moment.',
            errorCode: 'ai_temporarily_busy',
          );
        case 401:
        case 403:
          return const AskAIResponse(
            verdict: 'refused',
            type: 'general_qna',
            answer: 'The AI service is not configured correctly. Please try again later.',
            errorCode: 'ai_auth_error',
          );
        default:
          return const AskAIResponse(
            verdict: 'refused',
            type: 'general_qna',
            answer: 'Something went wrong on our side. Please try again.',
            errorCode: 'ai_error',
          );
      }
    }
    debugPrint('AI: request error: $e');
    return const AskAIResponse(
      verdict: 'refused',
      type: 'general_qna',
      answer: 'Something went wrong. Please check your internet connection and try again.',
      errorCode: 'network_error',
    );
  }

  // ── Device id (no sign-in) ───────────────────────────────────────────────
  static Future<String> deviceId() async {
    if (_deviceId != null) return _deviceId!;
    final prefs = await SharedPreferences.getInstance();
    var id = prefs.getString('ai_device_id');
    if (id == null) {
      id = 'd-${DateTime.now().microsecondsSinceEpoch.toRadixString(36)}';
      await prefs.setString('ai_device_id', id);
    }
    _deviceId = id;
    return id;
  }

  // ── Image OCR (ML Kit, on-device) ────────────────────────────────────────
  static Future<String> extractTextFromImage(XFile image) async {
    final inputImage = InputImage.fromFilePath(image.path);
    final recognizer = TextRecognizer();
    try {
      final result = await recognizer.processImage(inputImage);
      return result.text.trim();
    } finally {
      recognizer.close();
    }
  }

  // ── Voice (Android speech recognizer) ────────────────────────────────────
  static Future<String?> transcribe() async {
    if (!await Permission.microphone.request().isGranted) return null;

    final speech = SpeechToText();
    final available = await speech.initialize(
      onError: (e) => debugPrint('stt error: $e'),
      onStatus: (s) => debugPrint('stt status: $s'),
    );
    if (!available) return null;

    final completer = Completer<String?>();
    await speech.listen(
      listenOptions: SpeechListenOptions(
        listenFor: const Duration(seconds: 15),
        pauseFor: const Duration(seconds: 2),
        cancelOnError: true,
      ),
      onResult: (result) {
        if (result.finalResult) {
          if (!completer.isCompleted) completer.complete(result.recognizedWords);
        }
      },
    );

    String? words;
    try {
      words = await completer.future.timeout(
        const Duration(seconds: 16),
        onTimeout: () {
          if (!completer.isCompleted) completer.complete(null);
          return null;
        },
      );
    } catch (_) {
      words = null;
    }
    await speech.stop();
    return (words ?? '').trim().isEmpty ? null : words!.trim();
  }

  // ── Local history (no backend, no sign-in) ───────────────────────────────
  static const String _historyKey = 'ai_chat_history_v1';

  static Future<List<Map<String, dynamic>>?> loadHistory() async {
    final prefs = await SharedPreferences.getInstance();
    final raw = prefs.getString(_historyKey);
    if (raw == null) return null;
    try {
      final list = jsonDecode(raw) as List;
      return list
          .whereType<Map>()
          .map((e) => Map<String, dynamic>.from(e))
          .toList();
    } catch (_) {
      return null;
    }
  }

  static Future<void> saveHistory(List<Map<String, dynamic>> messages) async {
    final prefs = await SharedPreferences.getInstance();
    final top = messages.length > 120 ? messages.sublist(messages.length - 120) : messages;
    await prefs.setString(_historyKey, jsonEncode(top));
  }

  static Future<void> clearHistory() async {
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_historyKey);
  }
}

class _CorpusEntry {
  final int t;
  final dynamic data;
  _CorpusEntry(this.t, this.data);
}

class _GeminiHttpError implements Exception {
  final int status;
  final String message;
  _GeminiHttpError(this.status, this.message);
  @override
  String toString() => 'GeminiHttpError($status): $message';
}
